### PR TITLE
完成翻译:20181113 Building an API with GraphQL and Go

### LINKED ISSUE #916: 20181113 Building an API with GraphQL and Go
标题：Building an API with GraphQL and Go

原文链接：https://medium.com/@bradford_hamilton/building-an-api-with-graphql-and-go-9350df5c9356

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---

via: https://medium.com/@bradford_hamilton/building-an-api-with-graphql-and-go-9350df5c9356

作者：[Bradford Lamson-Scribner](https://medium.com/@bradford_hamilton?source=post_header_lockup)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

### PR DESCRIPTION
**Pull request by HelloJavaWorld123**
close #916

### CODE REVIEW

**Comment by polaris1119** [comment]
ci 不通过呢，处理下？

**Comment by HelloJavaWorld123** [comment]
> ci 不通过呢，处理下？

是怎么个不通过法？有没有哪里看错误或者原因的地方？

**Comment by polaris1119** [comment]
translated/tech/[20181113]-Building-an-API-with-GraphQL-and-Go.md:7: MD001 Header levels should only increment by one level at a time
translated/tech/[20181113]-Building-an-API-with-GraphQL-and-Go.md:24: MD009 Trailing spaces
translated/tech/[20181113]-Building-an-API-with-GraphQL-and-Go.md:6: MD012 Multiple consecutive blank lines
translated/tech/[20181113]-Building-an-API-with-GraphQL-and-Go.md:341: MD012 Multiple consecutive blank lines
translated/tech/[20181113]-Building-an-API-with-GraphQL-and-Go.md:460: MD012 Multiple consecutive blank lines

**Comment by polaris1119** [comment]
@HelloJavaWorld123 方便处理下吗？

**Comment by polaris1119** [comment]
因为译者长期不处理，merge 后我直接处理

**Pull request merged**
